#!/bin/bash

echo "=== Summary of Issue ==="
echo ""
echo "1. Latest commits pushed to GitHub:"
cd bol-outreach && git log --oneline -5
echo ""
echo "2. GitHub repository:"
cd bol-outreach && git remote -v
echo ""
echo "3. Latest Railway deployment (before recent commits):"
echo "   Time: 2026-02-12T10:33:57.409Z"
echo "   Status: SUCCESS"
echo ""
echo "4. Problem: Railway service is not auto-deploying latest commits"
echo ""
echo "=== Possible Causes ==="
echo ""
echo "1. Railway service not connected to GitHub repo"
echo "2. Railway service connected to different branch/repo"
echo "3. GitHub webhook not configured"
echo "4. Railway auto-deploy disabled"
echo ""
echo "=== Next Steps ==="
echo ""
echo "Option 1: Manual Railway Dashboard Configuration"
echo "   1. Visit https://railway.app/project/304d57d9-0378-4065-91ad-140105e7071c"
echo "   2. Open service: bol-outreach (0d8c45bd-2218-4766-b390-4d102b757157)"
echo "   3. Settings → GitHub → Connect repository"
echo "   4. Select: misto-guest/bol-outreach"
echo "   5. Set branch: main"
echo "   6. Enable auto-deploy on push"
echo ""
echo "Option 2: Create New Service"
echo "   1. Railway Dashboard → New Project → Deploy from GitHub"
echo "   2. Select: misto-guest/bol-outreach"
echo "   3. Configure settings from railway.toml"
echo ""
echo "Option 3: Use Railway CLI"
echo "   1. railway login"
echo "   2. cd bol-outreach"
echo "   3. railway up"
echo ""
echo "=== Test Endpoint After Fix ==="
echo "curl -X POST https://bol-outreach-production.up.railway.app/api/campaigns/1/sellers \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{\"sellerIds\":[1,2]}'"