#!/bin/bash

echo "🎙️ QuickTime Recording Setup"
echo "================================"
echo ""
echo "Opening QuickTime Player..."
open -a "QuickTime Player"

echo ""
echo "📝 Follow these steps:"
echo ""
echo "1. In QuickTime: File → New Audio Recording"
echo "2. Click the ▼ next to the red record button"
echo "3. Select 'BlackHole 2ch' as microphone"
echo "4. Click the red record button"
echo ""
echo "5. Play the YouTube video:"
echo "   https://m.youtube.com/watch?v=3BdFd1QBbp4"
echo "   Start from 33:26 (as you specified)"
echo ""
echo "6. When done, click stop in QuickTime"
echo "7. Save the file (建议 save to Desktop or Documents)"
echo ""
echo "8. Tell me the filename and I'll transcribe it!"
echo ""
echo "💡 Tip: Make sure BlackHole is set as your audio output"
echo "   in System Settings → Sound → Output"
